# Generated by Django 3.0.4 on 2021-03-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.IntegerField(default=0, verbose_name='Scene Id')),
                ('theta', models.FloatField(default=0.0, verbose_name='Button Rotation - Y')),
                ('parent_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.Scene')),
            ],
        ),
    ]
